apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: restcountries
  description: API pública para consultar información de países.
  tags:
    - rest
    - geo
    - paises
    - json
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  $openapi: https://raw.githubusercontent.com/gryphusimc/restcountries/master/openapi.yaml
