apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: restcountries
  annotations:
    github.com/project-slug: apilayer/restcountries
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
