apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: restcountries
  description: API pública para consultar información de países.
  tags:
    - rest
    - geo
    - países
    - json
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition: |
    openapi: 3.0.0
    info:
      title: REST Countries
      version: 1.0.0
    servers:
      - url: https://restcountries.com/v3.1
    paths:
      /all:
        get:
          summary: Obtener todos los países
          responses:
            '200':
              description: OK
